<script>
  import Grid from '$lib/components/layout/Grid.svelte'
  import Slide from '$lib/components/layout/Slide.svelte'
  import Interaction from './Interaction.svelte'
  import Poem from './Poem.svelte'
  import Software from './Software.svelte'
  import TitleSlide from './TitleSlide.svelte'

  import Ars_3 from '$assets/images/ars-3.jpg'
  import Bloomsbury from '$assets/images/bloomsbury.jpg'
  import ChassisMetal from '$assets/images/chassis-metal.jpg'
  import ChassisWood from '$assets/images/chassis-wood.jpg'
  import Crits_2 from '$assets/images/crits-2.jpg'
  import DetailsSlide from '$assets/images/details-slide.png'
  import LFA from '$assets/images/lfa.jpg'
  import PushUx_2 from '$assets/images/push-ux-2.jpg'
  import TedX_1 from '$assets/images/ted-x-1.jpg'

  import Deconstruction from '$assets/deconstruction.mp4'
  import Equipment from '$assets/images/equipment.jpg'
  import Intro from '$assets/intro.mp4'
  import MotorLoop from '$assets/motor_loop.mp4'
  import SlowPan from '$assets/slow_pan.mp4'
</script>

<!-- Introduction -->
<Slide image={DetailsSlide} />
<TitleSlide />
<section>
  <pre>
    <code class="language-js" data-trim>
      const james = [
        "software developer",
        "designer",
        "artist",   // apparently?
        "massive nerd"   // before it was cool
      ]
    </code>
  </pre>
</section>

<!-- Introducing Typo -->
<Slide video={Intro} loop />
<Interaction />
<Slide video={SlowPan} />

<!-- How does it work -->
<Slide title="bits & bobs" />
<Slide image={Equipment} />
<Slide>
  <Grid columns={2}>
    <img src={ChassisWood} alt="wooden chassis" />
    <img src={ChassisMetal} alt="metal chassis" />
  </Grid>
</Slide>

<Slide title="but where's the code?" />
<Software />

<Poem
  conversation={[
    { question: 'Make a wish!', answer: 'I want all the clouds to be pink' },
    {
      question: 'What makes your best friend unique?',
      answer: 'kindness',
    },
    { question: 'What made you smile today?', answer: ' working from home' },
  ]}
  seeds={['pink', 'kindness', 'home']}
  poem={'pink is the color of kindness\nthe hue of home\na gentle reminder that we are loved'}
/>
<Poem
  conversation={[
    { question: 'Coffee or tea?', answer: 't' },
    { question: 'What are you proud of?', answer: 'wearing glasses' },
    {
      question: 'What is the title of your favourite song?',
      answer: 'what a wonderful day',
    },
  ]}
  seeds={['t', 'wearing', 'wonderful']}
  poem={"My skin is wearing,\n wonderful wrinkles form.\nI'm still wonderful,\njust a little bit worn."}
/>
<Poem
  conversation={[
    { question: 'Make a wish!', answer: 'rainbow unicorn' },
    { question: 'What is the colour of your eyes?', answer: 'brown' },
    {
      question: 'Think of a bad habit you would like to quit.',
      answer: 'waking up late',
    },
  ]}
  seeds={['unicorn', 'brown', 'late']}
  poem={'There once was a Brown Unicorn,\nWho was Late for a Date with a Rhinoceros.'}
/>
<Slide iframe="https://typo.digital/generate/poetry" />
<Slide small caption={['example of poem generated by original ai']}>
  <p>
    hello we come of from darkness shall<br />
    thank and ever be because heart death and<br />
    brown the seem the body whose not<br />
  </p>
</Slide>

<Slide title="a helluva ride" />
<Slide
  image={Bloomsbury}
  caption={['DfPI Spring Show', '', 'Bloomsbury Theater, London (May 2022)']}
/>
<Slide
  image={Crits_2}
  caption={['Industry Showcase', '', 'Here East, London (June 2022)']}
/>
<Slide
  image={LFA}
  caption={[
    'London Festival of Architecture',
    '',
    'Here East, London (June 2022)',
  ]}
/>
<Slide
  image={TedX_1}
  caption={[
    'TEDx Goodenough College',
    '',
    'Goodenough College, London (July 2022)',
  ]}
/>
<Slide
  image={Ars_3}
  caption={['Ars Electronica', '', 'Linz, Austria (September 2022)']}
/>
<Slide
  image={PushUx_2}
  caption={['PUSH UX', '', 'Munich, Germany (November 2022)']}
/>

<Slide title="mistakes were made" />
<Slide
  iframe="https://gallery.autodesk.com/projects/172467/assets/664311/embed"
/>
<Slide video={MotorLoop} loop />

<Slide title="typo.digital" subtitle="james@james.mt" />

<Slide video={Deconstruction} />

<style lang="scss">
  p {
    font-size: 1.5rem;
    text-align: left;
  }
</style>
